### ISSUE TITLE
Docker Hub Authentication

### ISSUE THREAD

**Issue by MP-okui** [CircleCI-Public/azure-cli-orb#8]
I need to pass the docker auth parameter.
Are there any plans to support this?

[Docker Hub Authentication With Orb Executors](https://support.circleci.com/hc/en-us/articles/360051099071-Docker-Hub-Authentication-With-Orb-Executors)

**Comment by EricRibeiro** [comment]
Hi @MP-okui 👋 ,

Thank you for opening this issue.

The executors provided with the orb exist to cover most common scenarios. We can look into adding the auth parameter but the best solution for you is to provide the image parameter instead of the executor:

```
description: >
  Install the Azure CLI
usage:
  version: 2.1

  orbs:
    azure-cli: circleci/azure-cli@1.2.0

  jobs:
    verify-install:
      docker: 
         - image: mcr.microsoft.com/azure-cli
            auth:
              username: ...
              password: ...
      steps:
        - azure-cli/install

        - run:
            name: Verify Azure CLI is installed
            command: az -v

  workflows:
    example-workflow:
      jobs:
        - verify-install
```
